### ISSUE TITLE
Malformed HTML

### ISSUE THREAD

**Issue by AhmedNourJamalElDin** [jmriebold/BoilerPy3#2]
Hi,
Sometimes I pass HTML to get_doc, but it returns this warning with empty content:

```
WARNING:boilerpy3:Warning: SAX input contains nested A elements -- You have probably hit a bug in your HTML parser (e.g., NekoHTML bug #2909310). Please clean the HTML externally and feed it to BoilerPy3 again. Trying to recover somehow..
```
Any automated tips to fix this?

**Comment by jmriebold** [comment]
Hi @AhmedNourJamalElDin, I've come across that a few times as well, but haven't ever investigated the cause. Do you have any snippets that will reproduce the issue?

**Comment by AhmedNourJamalElDin** [comment]
I have opened a web page using chromium, then copied the html and passed it to `get_doc` of `CanolaExtractor`

TBH, I have two services, one to download the webpage using chromium, and the other one is Boilerpipe to extract the info of the webpage. When the first service downloads the page, it makes a request to boilerpipe service to extract the info. At this point, I get an empty content with the warning in the issue:

`WARNING:boilerpy3:Warning: SAX input contains nested A elements -- You have probably hit a bug in your HTML parser (e.g., NekoHTML bug #2909310). Please clean the HTML externally and feed it to BoilerPy3 again. Trying to recover somehow..
`

**Comment by jmriebold** [comment]
Yeah, we have a similar setup. Do you have some HTML that will reliably generate this error? I need an example to use while investigating the issue.

**Comment by AhmedNourJamalElDin** [comment]
Here is a link: http://www.elaosboa.news/21432
and its html as file: [malformed.zip](https://github.com/jmriebold/BoilerPy3/files/4003740/malformed.zip)

**Comment by jmriebold** [comment]
Thanks! I'll take a look.
