### ISSUE TITLE
need html with link

### ISSUE THREAD

**Issue by FaRzad-845** [jmriebold/BoilerPy3#6]
I want, when I give a link or HTML file to the program, I can finally get the output as HTML and also the links inside it. 

LIKE THIS: https://boilerpipe-web.appspot.com/extract?url=http%3A%2F%2Fwww.jahannews.com%2Fnews%2F769285%2Fkjhjkhk&extractor=ArticleExtractor&output=htmlFragment&extractImages=&token=

**Comment by jmriebold** [comment]
Hi @FaRzad-845, I've found a fixed a bug related to this functionality. See the [README](https://github.com/jmriebold/BoilerPy3/blob/master/README.md#marked-html-extraction) for details on how to get the filtered HTML.
